### ISSUE TITLE
Inflate error - cannot parse TextView

### ISSUE THREAD

**Issue by bartekpacia** [tingyik90/snackprogressbar#22]
version: 6.1 (apparently, it's also broken) 

 Calling 
```
snackProgressBarManager.show(snackProgressBar, SnackProgressBarManager.LENGTH_INDEFINITE)
```
produces
```
 android.view.InflateException: Binary XML file line #129: Error inflating class TextView
...
... (lots of logs)
...
Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 5
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
        at android.widget.TextView.<init>(TextView.java:1032)
        at android.widget.TextView.<init>(TextView.java:674)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1371)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1421)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at com.tingyik90.snackprogressbar.SnackProgressBarCore$Companion.make$lib_release(SnackProgressBarCore.kt:71) 
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.playQueue(SnackProgressBarManager.kt:552) 
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.addToQueue(SnackProgressBarManager.kt:517) 
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.show(SnackProgressBarManager.kt:263) 
        at pl.baftek.discoverrudy.place.PlaceActivity.showSnackbar(PlaceActivity.kt:325) 
        at pl.baftek.discoverrudy.place.PlaceActivity.showVisits(PlaceActivity.kt:279) 
        at pl.baftek.discoverrudy.place.PlaceActivity.access$showVisits(PlaceActivity.kt:36) 
        at pl.baftek.discoverrudy.place.PlaceActivity$onCreate$12.onClick(PlaceActivity.kt:165) 
        at android.view.View.performClick(View.java:4764) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:125) 
        at android.view.View$PerformClick.run(View.java:19844) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5349) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 

```

Looks like something related to the TextView on SnackProgressBar.

**Comment by tingyik90** [comment]
Hi @bartekpacia, this is really weird because it is working nicely on my other apps. Can you please let me know the specific `snackProgressBar` configuration that you are using? The statement `Failed to resolve attribute at index 5` might mean that you are not providing the required resources. See [this](https://stackoverflow.com/a/30606044/3584439).

**Comment by tingyik90** [comment]
I'm not sure if this is related, but apparently I missed out the fourth constructor of LinearLayout in SnackProgressBarLayout, which may be the reason the TextView cannot find certain resources required (your activity layout may contain some custom resources?).

```
@TargetApi(21)
    constructor(
        context: Context,
        attrs: AttributeSet?,
        defStyleAttr: Int,
        defStyleRes: Int
    ) : super(context, attrs, defStyleAttr, defStyleRes)
```

I've added the fourth constructor in. Please give `implementation 'com.github.tingyik90:snackprogressbar:c4a1fb7467'` a try.

**Comment by Anvipo** [comment]
Hi @tingyik90.
I faced same error in my app. Even using c4a1fb7467 commit, error still occurs.

My stacktrace:
`android.view.InflateException: Binary XML file line #129: Binary XML file line #129: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #129: Error inflating class TextView
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f030087 a=7 r=0x7f05002c}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
        at android.widget.TextView.readTextAppearance(TextView.java:3557)
        at android.widget.TextView.<init>(TextView.java:974)
        at android.widget.TextView.<init>(TextView.java:879)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.tingyik90.snackprogressbar.SnackProgressBarCore$Companion.make$lib_release(SnackProgressBarCore.kt:73)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.playQueue(SnackProgressBarManager.kt:556)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.addToQueue(SnackProgressBarManager.kt:521)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.show(SnackProgressBarManager.kt:267)
        at com.anvipo.angram.coreLayer.base.baseClasses.BaseActivity.showSnackMessage(BaseActivity.kt:62)
        at com.anvipo.angram.applicationLayer.launchSystem.appActivity.view.AppView$$State.showSnackMessage(AppView$$State.java:102)
        at com.anvipo.angram.applicationLayer.launchSystem.appActivity.presenter.AppPresenterImp$subscribeOnConnectionStates$1$1.invokeSuspend(AppPresenterImp.kt:183)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

You can build and run code from branch [https://github.com/Anvipo/AnGram/tree/feature/add-snackprogressbar](url) and you will see the error. May be it will help you to find out the reason of that error.

**Comment by tingyik90** [comment]
@Anvipo, thanks for the github repo! As I am unfamiliar with your codes, can you point out which activity and resources that are relevant? I'll give it a look. Did you have this issue with v5.0?

**Comment by Anvipo** [comment]
@tingyik90, sure, I can.
Error occurs in file BaseActivity at 62nd line of code at `snackProgressBarManager.show` method.
SnackProgressBarManager uses FrameLayout (from layout_container.xml file) as view.

**Comment by Anvipo** [comment]
Just tried v5,0 and same error occurs.
Here stacktrace:
`android.view.InflateException: Binary XML file line #133: Binary XML file line #133: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #133: Error inflating class TextView
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f030087 a=7 r=0x7f05002c}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
        at android.widget.TextView.readTextAppearance(TextView.java:3557)
        at android.widget.TextView.<init>(TextView.java:974)
        at android.widget.TextView.<init>(TextView.java:879)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.tingyik90.snackprogressbar.SnackProgressBarCore$Companion.make$lib_release(SnackProgressBarCore.kt:51)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.playQueue(SnackProgressBarManager.kt:495)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.addToQueue(SnackProgressBarManager.kt:470)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.show(SnackProgressBarManager.kt:226)
        at com.anvipo.angram.coreLayer.base.baseClasses.BaseActivity.showSnackMessage(BaseActivity.kt:67)
        at com.anvipo.angram.applicationLayer.launchSystem.appActivity.view.AppView$$State.showSnackMessage(AppView$$State.java:102)
        at com.anvipo.angram.applicationLayer.launchSystem.appActivity.presenter.AppPresenterImp$subscribeOnConnectionStates$1$1.invokeSuspend(AppPresenterImp.kt:183)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by tingyik90** [comment]
This is good to know, which means that something is not right since the beginning, not just v6.0. Can you let me know your Android API level that this crash occurs?

**Comment by Anvipo** [comment]
Android 9 Pie (sdk version 28)

**Comment by tingyik90** [comment]
@Anvipo, I think the issue is with the layoutres file used. Please point me to the layout of the activity. I need your help to provide a minimum working example that causes this crash. I can't go through the whole code to determine which part is causing the crash.

**Comment by Anvipo** [comment]
@tingyik90, the layout of the activity - layout_container.xml.
Error occurs in file BaseActivity.kt at 62nd line of code at snackProgressBarManager.show() method.
Branch feature/add-snackprogressbar provides a minimum working example that causes this crash.
You need only to build and run code from that branch on your device.

**Comment by bartekpacia** [comment]
In 6.1.1 the same bug occurs (I described in the first post, logs are the same too).
By looking at the logs I think something's wrong with the these TextViews

https://github.com/tingyik90/snackprogressbar/blob/c4a1fb74670edeb66404822cc3d2f829acf8b477/lib/src/main/res/layout/snackprogressbar.xml#L115-L141

**Comment by tingyik90** [comment]
@Anvipo @bartekpacia, I finally have time to clone the repo and did some test. Apparently, this is an issue from your side where you did not declare `<color name="colorAccent">#03A9F4</color>` in your `res`. The name `color name="accent"` was used which caused the property lookup to fail. 

Internally, `colors.xml` is looking up what colorAccent is applied by the user via `?attr/colorAccent`. You can easily fix this by just adding `colorAccent` into your `colors.xml`. Please try and let me know if it solves your problem.

**Comment by Anvipo** [comment]
@tingyik90, yep, I got this, thank you.
I've renamed color "accent" to "colorAccent" and it works.
P.S. That was funny. :)
