### ISSUE TITLE
Error on method subscribe

### ISSUE THREAD

**Issue by ghost** [tingyik90/snackprogressbar#3]
Hello, I'm using the EventBus lib and in the "Subscribe method" of EventBus I'm creating the SnackBar like so:

```
determinateSnackBar = new SnackProgressBar(
                SnackProgressBar.TYPE_DETERMINATE, "TYPE_DETERMINATE.")
                .setShowProgressPercentage(true)
                .setAllowUserInput(true)
                .setProgressMax(100);

snackProgressBarManager.show(determinateSnackBar,
                SnackProgressBarManager.LENGTH_INDEFINITE);
```

But in the .show method of the snackProgressBarManager I'm getting the following error:

> Hello, I'm using the EventBus lib and in the "Subscribe method" of EventBus I'm creating the SnackBar like so:

```
determinateSnackBar = new SnackProgressBar(
                SnackProgressBar.TYPE_DETERMINATE, "TYPE_DETERMINATE.")
                .setShowProgressPercentage(true)
                .setAllowUserInput(true)
                .setProgressMax(100);

snackProgressBarManager.show(determinateSnackBar,
                SnackProgressBarManager.LENGTH_INDEFINITE);
```

But in the .show method of the snackProgressBarManager I'm getting the following error:

> 08-25 17:16:20.122 32291-619/com.ricardo.example E/EventBus: Could not dispatch event: class com.ricardo.example.controllers.events.SearchPickingListEvent to subscribing class class com.ricardo.example.activities.HomeActivity
                                                                      android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                          at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6149)
                                                                          at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:843)
                                                                          at android.view.View.requestLayout(View.java:16474)
                                                                          at android.view.View.requestLayout(View.java:16474)
                                                                          at android.view.View.requestLayout(View.java:16474)
                                                                          at android.view.View.requestLayout(View.java:16474)
                                                                          at android.view.View.requestLayout(View.java:16474)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:3415)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:3362)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:3338)
                                                                          at com.tingyik90.snackprogressbar.SnackProgressBarCore.make(SnackProgressBarCore.java:55)
                                                                          at com.tingyik90.snackprogressbar.SnackProgressBarManager.playQueue(SnackProgressBarManager.java:485)
                                                                          at com.tingyik90.snackprogressbar.SnackProgressBarManager.addToQueue(SnackProgressBarManager.java:461)
                                                                          at com.tingyik90.snackprogressbar.SnackProgressBarManager.show(SnackProgressBarManager.java:232)
                                                                          at com..ricardo.example.activities.HomeActivity.showSnackBar(HomeActivity.java:209)
                                                                          at com..ricardo.example.activities.HomeActivity.onSearchPinckingListEvent(HomeActivity.java:188)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                          at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
                                                                          at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:841)
08-25 17:16:20.123 32291-619/com.ricardo.example D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent

**Comment by tingyik90** [comment]
I am not familiar with Eventbus, but the main error is on this line `android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.`
You are running some callback from another thread and you cannot update the View unless you are on the main thread. This might solve your problem https://stackoverflow.com/questions/29040333/eventbus-not-on-the-main-thread. 
Let me know the result so I can close this issue.

**Comment by ghost** [comment]
Yes, this is solution! Tks
